name: YOLO
server:
  cut-module: b #or b, c, đây chỉ là cái cố định
  clients: # định nghĩa 3 clident với id đều là 1
    - 1
    - 1 
    - 1
  model: yolov8_version1 # đây chính là tên file tham số cho model, phiên bản càng cao khả năng nhận diện của model càng được nâng lên
  batch-frame: 1 # chính là số khung hình xử lý đồng thời
rabbit:
  address: 127.0.0.1
  username: guest
  password: guest
  virtual-host: /

data: src/img1.jpg
log-path: .
control-count: 10
debug-mode: False
